spring:
  application:
    name: FinanceApp
  datasource:
    url: "endereço do banco"
    username: "usuário do banco"
    password: "senha do banco"
  jpa:
    hibernate:
      ddl-auto: validate
  web:
    error:
      include-stacktrace: never

keys:
  secret: "sua chave aqui"
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    try-it-out-enabled: true
